# Generated by Django 5.1.6 on 2025-03-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_mealplan_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
