# Generated by Django 5.1.6 on 2025-03-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_is_scheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_sub',
        ),
    ]
