# Generated by Django 5.1.7 on 2025-03-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_guestorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighttracking',
            name='health_status',
            field=models.CharField(default='Not rated yet', max_length=50),
        ),
    ]
