# Generated by Django 5.1.7 on 2025-03-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
